// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUEp1TkH1X9QSxBcPnxCNj-qWiXaFLfw',
    appId: '1:422894440086:web:ea432f4c13617de6d3bcb7',
    messagingSenderId: '422894440086',
    projectId: 'highball-109e9',
    authDomain: 'highball-109e9.firebaseapp.com',
    storageBucket: 'highball-109e9.appspot.com',
    measurementId: 'G-99HMJH0SQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3k3IyUFSqc4JP9wyf68lcLiEB9WmlXRE',
    appId: '1:422894440086:android:f19a99a95216f8f4d3bcb7',
    messagingSenderId: '422894440086',
    projectId: 'highball-109e9',
    storageBucket: 'highball-109e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCezJcL8WrdqfafW7pqzoCdCxNSPR1JewM',
    appId: '1:422894440086:ios:21c4e5dc910273bdd3bcb7',
    messagingSenderId: '422894440086',
    projectId: 'highball-109e9',
    storageBucket: 'highball-109e9.appspot.com',
    iosBundleId: 'com.example.highball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCezJcL8WrdqfafW7pqzoCdCxNSPR1JewM',
    appId: '1:422894440086:ios:21c4e5dc910273bdd3bcb7',
    messagingSenderId: '422894440086',
    projectId: 'highball-109e9',
    storageBucket: 'highball-109e9.appspot.com',
    iosBundleId: 'com.example.highball',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjUEp1TkH1X9QSxBcPnxCNj-qWiXaFLfw',
    appId: '1:422894440086:web:ac4b0c32015c75dfd3bcb7',
    messagingSenderId: '422894440086',
    projectId: 'highball-109e9',
    authDomain: 'highball-109e9.firebaseapp.com',
    storageBucket: 'highball-109e9.appspot.com',
    measurementId: 'G-8MPHX3VD1J',
  );

}